### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by meowerkiu** [paaiz/GrowStore#1]

**Comment by paaiz** [comment]
to run the bot, you can just do "node src/index.js" without the ""

**Comment by meowerkiu** [comment]
cant

**Comment by meowerkiu** [comment]
![Uploading Screenshot_2024-11-20-13-44-09-464_com.server.auditor.ssh.client.jpg…]()

**Comment by meowerkiu** [comment]
> to run the bot, you can just do "node src/index.js" in the terminal/cmd without the ""

how to fix
